package Interfaces;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asmz
 */
import Project.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
    }

    // Helper method to refresh the room list in the table
    private void refreshRoomList() {
        DefaultTableModel model = (DefaultTableModel) tblManageRoom.getModel();
        model.setRowCount(0); // Clear the table content

        // Retrieve the updated room list from the database
        ResultSet rs = Select.getData("SELECT * FROM room");

        try {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ROOMNO"),
                    rs.getString("ROOMTYPE"),
                    rs.getString("BED"),
                    rs.getString("PRICE"),
                    rs.getString("STATUS")
                });
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageRoom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbBed = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAddRoom = new javax.swing.JButton();
        rtbAc = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Manage Room");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tblManageRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Nnumber", "Room Type", "Bed", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblManageRoom);

        jLabel2.setText("Room Number");

        jLabel3.setText("Room Type");

        cmbBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));

        jLabel4.setText("Bed");

        jLabel5.setText("Price");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        btnAddRoom.setText("Addd Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        buttonGroup1.add(rtbAc);
        rtbAc.setText("AC");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Non-AC");

        btnDeleteRoom.setText("Delete Room");
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(txtRoomNumber)
                        .addComponent(jLabel3)
                        .addComponent(cmbBed, 0, 197, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(txtPrice))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddRoom)
                        .addGap(78, 78, 78)
                        .addComponent(btnDeleteRoom))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtbAc)
                        .addGap(40, 40, 40)
                        .addComponent(jRadioButton2)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnClose))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtbAc)
                            .addComponent(jRadioButton2))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddRoom)
                            .addComponent(btnDeleteRoom)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        // Get the values from the input fields
        String roomNo = txtRoomNumber.getText().trim();
        String roomType = rtbAc.isSelected() ? "AC" : "Non-AC";
        String bed = (String) cmbBed.getSelectedItem();
        String price = txtPrice.getText().trim();

        // Validate the input fields
        if (roomNo.isEmpty() || roomType.isEmpty() || bed.isEmpty() || price.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all the fields.");
            return;
        }

        // Validate room number format (integer)
        try {
            int roomNumber = Integer.parseInt(roomNo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid room number. Please enter a valid integer.");
            return;
        }

        // Validate price format (double)
        try {
            double roomPrice = Double.parseDouble(price);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid price. Please enter a valid number.");
            return;
        }

        // Check if the room number is already in use
        if (isRoomNumberExists(roomNo)) {
            JOptionPane.showMessageDialog(null, "Room number already exists. Please enter a different room number.");
            return;
        }

        // Construct the INSERT query
        String query = "INSERT INTO room (ROOMNO, ROOMTYPE, bed, price, status) VALUES (?, ?, ?, ?, 'Available')";

        try ( Connection con = ConnectionProvider.getCon();  PreparedStatement pstmt = con.prepareStatement(query)) {

            // Set the parameter values in the query
            pstmt.setString(1, roomNo);
            pstmt.setString(2, roomType);
            pstmt.setString(3, bed);
            pstmt.setString(4, price);

            // Execute the INSERT query
            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Room added successfully.");

                // Clear the input fields
                txtRoomNumber.setText("");
                rtbAc.setSelected(true);
                cmbBed.setSelectedIndex(0);
                txtPrice.setText("");

                // Refresh the room list in the table
                refreshRoomList();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add room.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private boolean isRoomNumberExists(String roomNo) {
        String query = "SELECT COUNT(*) FROM room WHERE ROOMNO = ?";

        try ( Connection con = ConnectionProvider.getCon();  PreparedStatement pstmt = con.prepareStatement(query)) {

            pstmt.setString(1, roomNo);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                int count = rs.getInt(1);
                return count > 0;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return false;


    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = Select.getData("SELECT * FROM room");
        DefaultTableModel model = (DefaultTableModel) tblManageRoom.getModel();

        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        // TODO add your handling code here:
        // Get the selected row from the table
        int selectedRow = tblManageRoom.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a room to delete.");
            return;
        }

        // Get the room number and status from the selected row
        String roomNo = tblManageRoom.getValueAt(selectedRow, 0).toString();
        String status = tblManageRoom.getValueAt(selectedRow, 4).toString();

        // Check if the room is available for deletion
        if (status.equals("Available")) {
            // Confirm the deletion with the user
            int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete room " + roomNo + "?", "Confirmation", JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.YES_OPTION) {
                // Construct the DELETE query
                String query = "DELETE FROM room WHERE ROOMNO = ?";

                try ( Connection con = ConnectionProvider.getCon();  PreparedStatement pstmt = con.prepareStatement(query)) {

                    // Set the room number parameter in the query
                    pstmt.setString(1, roomNo);

                    // Execute the DELETE query
                    int rowsAffected = pstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Room deleted successfully.");

                        // Refresh the room list in the table
                        refreshRoomList();
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to delete room.");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cannot delete room. It is currently unavailable.");
        }
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        // Get the selected row from the table
        int selectedRow = tblManageRoom.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a room to edit.");
            return;
        }

        // Get the existing room details from the selected row
        String existingRoomNo = tblManageRoom.getValueAt(selectedRow, 0).toString();
        String existingRoomType = tblManageRoom.getValueAt(selectedRow, 1).toString();
        String existingBed = tblManageRoom.getValueAt(selectedRow, 2).toString();
        String existingPrice = tblManageRoom.getValueAt(selectedRow, 3).toString();

        // Show a dialog to edit the room details
        RoomEditDialog editDialog = new RoomEditDialog(this, true);
        editDialog.setRoomDetails(existingRoomNo, existingRoomType, existingBed, existingPrice);
        editDialog.setVisible(true);

        // Check if the dialog was closed by clicking the "Save" button
        if (editDialog.isSaveButtonClicked()) {
            // Retrieve the modified room details from the dialog
            String modifiedRoomNo = editDialog.getRoomNumber();
            String modifiedRoomType = editDialog.getRoomType();
            String modifiedBed = editDialog.getBedType();
            String modifiedPrice = editDialog.getPrice();

            // Validate the modified room details
            if (modifiedRoomNo.isEmpty() || modifiedRoomType.isEmpty() || modifiedBed.isEmpty() || modifiedPrice.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all the fields.");
                return;
            }

            // Validate modified room number format (integer)
            try {
                int roomNumber = Integer.parseInt(modifiedRoomNo);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid room number. Please enter a valid integer.");
                return;
            }

            // Validate modified price format (double)
            try {
                double roomPrice = Double.parseDouble(modifiedPrice);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid price. Please enter a valid number.");
                return;
            }

            // Check if the modified room number already exists
            if (!modifiedRoomNo.equals(existingRoomNo) && isRoomNumberExists(modifiedRoomNo)) {
                JOptionPane.showMessageDialog(null, "Room number already exists. Please enter a different room number.");
                return;
            }

            // Construct the UPDATE query
            String query = "UPDATE room SET ROOMNO = ?, ROOMTYPE = ?, BED = ?, PRICE = ? WHERE ROOMNO = ?";
            
            modifiedRoomNo=(String)tblManageRoom.getValueAt(tblManageRoom.getSelectedRow(),0);
            modifiedRoomType=(String)tblManageRoom.getValueAt(tblManageRoom.getSelectedRow(),0);

            try ( Connection con = ConnectionProvider.getCon();  PreparedStatement pstmt = con.prepareStatement(query)) {

                // Set the parameter values in the query
                pstmt.setString(1, modifiedRoomNo);
                pstmt.setString(2, modifiedRoomType);
                pstmt.setString(3, modifiedBed);
                pstmt.setString(4, modifiedPrice);
                pstmt.setString(5, existingRoomNo);

                // Execute the UPDATE query
                int rowsAffected = pstmt.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Room updated successfully.");

                    // Refresh the room list in the table
                    refreshRoomList();
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to update room.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbBed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rtbAc;
    private javax.swing.JTable tblManageRoom;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNumber;
    // End of variables declaration//GEN-END:variables
}
