
import project.Data;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asmz
 */
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import project.Room;
import project.*;

public class CustomerCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckIn
     */
    public CustomerCheckIn() {
        initComponents();
        checkInDateJTextField.setEditable(false);
        priceJTextField.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("dd / MM / yyyy");
        //Calendar cal = Calendar.getInstance();
        Date date = new Date();
        //checkInDateJTextField.setText(myFormat.format(cal.getTime()));
        checkInDateJTextField.setText(myFormat.format(date));
        ShowRoomNumbers();
///////////////////////////////////////////////////////
    }

    private void ShowRoomNumbers() {
        roomNumberJComboBox.removeAllItems();
        for (Room room : Data.rooms) {
            roomNumberJComboBox.addItem(Integer.toString(room.getRoomNumber()));
        }
    }
    String bed;
    String roomType;
    String roomNumber;
    String price;

    public void roomDetails() {
        // Declare variables outside of try/catch block
        String bed = (String) bedJComboBox.getSelectedItem();
        String roomType = (String) roomTypeJComboBox.getSelectedItem();
        String roomNumber = null;
        String price = null;

        // Clear combobox and textfield
        roomNumberJComboBox.removeAllItems();
        priceJTextField.setText("");

        try {
            // Loop through rooms
            for (Room room : Data.rooms) {
                // Check if room matches selected bed and room type, and is available
                if (room.getBed().equals(bed) && room.getRoomType().equals(roomType) && room.getAvailability().equals("Available")) {
                    // Add room number to combobox
                    roomNumberJComboBox.addItem(Integer.toString(room.getRoomNumber()));

                    // Set price in textfield
                    price = Integer.toString(((int) room.getPrice()));
                    priceJTextField.setText(price);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void idNumberPassportJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }

    private void mobileNumberJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        customerCheckInJLabel = new javax.swing.JLabel();
        closeJButton = new javax.swing.JButton();
        nameSurnameJLabel = new javax.swing.JLabel();
        nameSurnameJTextField = new javax.swing.JTextField();
        mobileNumberJLabel = new javax.swing.JLabel();
        mobileNumberJTextField = new javax.swing.JTextField();
        nationalityJLabel = new javax.swing.JLabel();
        nationalityJTextField = new javax.swing.JTextField();
        genderJLabel = new javax.swing.JLabel();
        genderMaleJRadioButton = new javax.swing.JRadioButton();
        genderFemaleJRadioButton = new javax.swing.JRadioButton();
        emailJLabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        idNumberPassportJLabel = new javax.swing.JLabel();
        idNumberPassportJTextField = new javax.swing.JTextField();
        adressLabel = new javax.swing.JLabel();
        adressJTextField = new javax.swing.JTextField();
        checkInDateJLabel = new javax.swing.JLabel();
        checkInDateJTextField = new javax.swing.JTextField();
        bedJLabel = new javax.swing.JLabel();
        bedJComboBox = new javax.swing.JComboBox<>();
        roomTypeJLabel = new javax.swing.JLabel();
        roomTypeJComboBox = new javax.swing.JComboBox<>();
        roomNumberJLabel = new javax.swing.JLabel();
        roomNumberJComboBox = new javax.swing.JComboBox<>();
        priceJLabel = new javax.swing.JLabel();
        priceJTextField = new javax.swing.JTextField();
        reserveRoomJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        VIPJCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);

        customerCheckInJLabel.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        customerCheckInJLabel.setForeground(new java.awt.Color(51, 0, 0));
        customerCheckInJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-in.png"))); // NOI18N
        customerCheckInJLabel.setText("Cutomer Check IN");

        closeJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        nameSurnameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameSurnameJLabel.setText("Name / Surname");

        nameSurnameJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameSurnameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSurnameJTextFieldActionPerformed(evt);
            }
        });

        mobileNumberJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobileNumberJLabel.setText("Mobile Number");

        mobileNumberJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobileNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumberJTextFieldActionPerformed(evt);
            }
        });

        nationalityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nationalityJLabel.setText("Nationality");

        nationalityJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nationalityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityJTextFieldActionPerformed(evt);
            }
        });

        genderJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderJLabel.setText("Gender");

        buttonGroup1.add(genderMaleJRadioButton);
        genderMaleJRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderMaleJRadioButton.setText("Male");

        buttonGroup1.add(genderFemaleJRadioButton);
        genderFemaleJRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderFemaleJRadioButton.setText("Female");
        genderFemaleJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFemaleJRadioButtonActionPerformed(evt);
            }
        });

        emailJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailJLabel.setText("Email");

        emailJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        idNumberPassportJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idNumberPassportJLabel.setText("ID Number / Passport");

        idNumberPassportJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        adressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adressLabel.setText("Adress");

        adressJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        checkInDateJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInDateJLabel.setText("Check IN Date (Today)");

        checkInDateJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInDateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInDateJTextFieldActionPerformed(evt);
            }
        });

        bedJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bedJLabel.setText("Bed");

        bedJComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bedJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        bedJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedJComboBoxActionPerformed(evt);
            }
        });

        roomTypeJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomTypeJLabel.setText("Room Type");

        roomTypeJComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        roomTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeJComboBoxActionPerformed(evt);
            }
        });

        roomNumberJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomNumberJLabel.setText("Room Number");

        roomNumberJComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomNumberJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberJComboBoxActionPerformed(evt);
            }
        });

        priceJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        priceJLabel.setText("Price");

        priceJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        priceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceJTextFieldActionPerformed(evt);
            }
        });

        reserveRoomJButton.setBackground(new java.awt.Color(102, 0, 0));
        reserveRoomJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reserveRoomJButton.setForeground(new java.awt.Color(255, 255, 255));
        reserveRoomJButton.setText("Reserve Room");
        reserveRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveRoomJButtonActionPerformed(evt);
            }
        });

        clearJButton.setBackground(new java.awt.Color(102, 0, 0));
        clearJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearJButton.setForeground(new java.awt.Color(255, 255, 255));
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        VIPJCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VIPJCheckBox.setText("VIP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(nameSurnameJLabel)
                                .addGap(277, 277, 277)
                                .addComponent(idNumberPassportJLabel)
                                .addGap(285, 285, 285)
                                .addComponent(bedJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameSurnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(idNumberPassportJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(bedJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mobileNumberJLabel)
                                .addGap(288, 288, 288)
                                .addComponent(adressLabel)
                                .addGap(385, 385, 385)
                                .addComponent(roomTypeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mobileNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(adressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(roomTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nationalityJLabel)
                                .addGap(319, 319, 319)
                                .addComponent(checkInDateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(237, 237, 237)
                                .addComponent(roomNumberJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nationalityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(checkInDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(roomNumberJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderJLabel)
                                .addGap(774, 774, 774)
                                .addComponent(priceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(genderMaleJRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(genderFemaleJRadioButton))
                                    .addComponent(emailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(672, 672, 672)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(VIPJCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customerCheckInJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeJButton)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reserveRoomJButton)
                .addGap(88, 88, 88)
                .addComponent(clearJButton)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerCheckInJLabel)
                    .addComponent(closeJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSurnameJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idNumberPassportJLabel)
                            .addComponent(bedJLabel))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSurnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNumberPassportJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobileNumberJLabel)
                    .addComponent(adressLabel)
                    .addComponent(roomTypeJLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobileNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationalityJLabel)
                    .addComponent(checkInDateJLabel)
                    .addComponent(roomNumberJLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationalityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkInDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNumberJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderJLabel)
                    .addComponent(priceJLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderMaleJRadioButton)
                            .addComponent(genderFemaleJRadioButton))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailJLabel)
                    .addComponent(VIPJCheckBox))
                .addGap(12, 12, 12)
                .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveRoomJButton)
                    .addComponent(clearJButton))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameSurnameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSurnameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSurnameJTextFieldActionPerformed

    private void nationalityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityJTextFieldActionPerformed

    private void checkInDateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInDateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInDateJTextFieldActionPerformed

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        // TODO add your handling code here:
        if (true) {
            dispose();
        }
    }//GEN-LAST:event_closeJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void roomNumberJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberJComboBoxActionPerformed
        // TODO add your handling code here:
        String roomNumber = (String) roomNumberJComboBox.getSelectedItem();
        for (Room room : Data.rooms) {
            if (Integer.toString(room.getRoomNumber()).equals(roomNumber)) {
                priceJTextField.setText(String.valueOf(room.getPrice()));
                break;
            }
        }
    }//GEN-LAST:event_roomNumberJComboBoxActionPerformed

    private void roomTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeJComboBoxActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_roomTypeJComboBoxActionPerformed

    private void bedJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedJComboBoxActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_bedJComboBoxActionPerformed

    private void reserveRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveRoomJButtonActionPerformed
        // TODO add your handling code here:                                               
        // Get the customer information from the text fields
        int id = 1;
        String name = nameSurnameJTextField.getText();
        String mobileNumber = mobileNumberJTextField.getText();
        String nationality = nationalityJTextField.getText();
        String gender = "";
        if (genderMaleJRadioButton.isSelected()) {
            gender = "Male";
        } else if (genderFemaleJRadioButton.isSelected()) {
            gender = "Female";
        }
        String email = emailJTextField.getText();
        String idNumberPassport = idNumberPassportJTextField.getText();
        String address = adressJTextField.getText();
        String checkIn = checkInDateJTextField.getText();
        String bed = (String) bedJComboBox.getSelectedItem();
        String roomType = (String) roomTypeJComboBox.getSelectedItem();
        String roomNumber = (String) roomNumberJComboBox.getSelectedItem();
        String price = priceJTextField.getText();

        for (Room room : Data.rooms) {
            if (Integer.toString(room.getRoomNumber()).equals(roomNumber)) {
                room.setAvailability("Unavailable");
                break;
            }
        }

        JOptionPane.showMessageDialog(null, "Customer Check In Successfully");
        setVisible(false);
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_reserveRoomJButtonActionPerformed

    private void mobileNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumberJTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mobileNumberJTextFieldActionPerformed

    private void genderFemaleJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFemaleJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFemaleJRadioButtonActionPerformed

    private void priceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox VIPJCheckBox;
    private javax.swing.JTextField adressJTextField;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JComboBox<String> bedJComboBox;
    private javax.swing.JLabel bedJLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel checkInDateJLabel;
    private javax.swing.JTextField checkInDateJTextField;
    private javax.swing.JButton clearJButton;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel customerCheckInJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JRadioButton genderFemaleJRadioButton;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JRadioButton genderMaleJRadioButton;
    private javax.swing.JLabel idNumberPassportJLabel;
    private javax.swing.JTextField idNumberPassportJTextField;
    private javax.swing.JLabel mobileNumberJLabel;
    private javax.swing.JTextField mobileNumberJTextField;
    private javax.swing.JLabel nameSurnameJLabel;
    private javax.swing.JTextField nameSurnameJTextField;
    private javax.swing.JLabel nationalityJLabel;
    private javax.swing.JTextField nationalityJTextField;
    private javax.swing.JLabel priceJLabel;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JButton reserveRoomJButton;
    private javax.swing.JComboBox<String> roomNumberJComboBox;
    private javax.swing.JLabel roomNumberJLabel;
    private javax.swing.JComboBox<String> roomTypeJComboBox;
    private javax.swing.JLabel roomTypeJLabel;
    // End of variables declaration//GEN-END:variables
}
