/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asmz
 */
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.Room;
import project.*;

public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() {
        initComponents();
        customerNameJTextField.setEditable(false);
        checkInJTextField.setEditable(false);
        checkOutJTextField.setEditable(false);
        mobileNumberJTextField.setEditable(false);
        pricePerDayJTextField.setEditable(false);
        numberOfDaysStayJTextField.setEditable(false);
        totalPriceJTextField.setEditable(false);
        emailJTextField.setEditable(false);
    }

    
    ArrayList<Customers> customer = new ArrayList<Customers>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        roomNumberJLabel = new javax.swing.JLabel();
        roomNumberJTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerInformationJTable = new javax.swing.JTable();
        customerNameJLabel = new javax.swing.JLabel();
        customerNameJTextField = new javax.swing.JTextField();
        checkInJLabel = new javax.swing.JLabel();
        checkInJTextField = new javax.swing.JTextField();
        checkOutJLabel = new javax.swing.JLabel();
        checkOutJTextField = new javax.swing.JTextField();
        mobileNumberJLabel = new javax.swing.JLabel();
        mobileNumberJTextField = new javax.swing.JTextField();
        pricePerDayJLabel = new javax.swing.JLabel();
        pricePerDayJTextField = new javax.swing.JTextField();
        numberOfDaysStayJLabel = new javax.swing.JLabel();
        numberOfDaysStayJTextField = new javax.swing.JTextField();
        totalPriceJLabel = new javax.swing.JLabel();
        totalPriceJTextField = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        checkOutJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-out.png"))); // NOI18N
        jLabel1.setText("Customer Check-Out");

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        roomNumberJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomNumberJLabel.setText("Room Number");

        roomNumberJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        customerInformationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Mobile Number", "Nationality", "Gender", "Email", "Passport", "Adress", "CheckIN Date", "Room Number", "Bed", "Room Type", "price per day"
            }
        ));
        jScrollPane1.setViewportView(customerInformationJTable);

        customerNameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerNameJLabel.setText("Customer Name");

        customerNameJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameJTextFieldActionPerformed(evt);
            }
        });

        checkInJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInJLabel.setText("Check-IN Date");

        checkInJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInJTextFieldActionPerformed(evt);
            }
        });

        checkOutJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkOutJLabel.setText("Check-Out Date (Today)");

        checkOutJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mobileNumberJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobileNumberJLabel.setText("Customer Mobile Number");

        mobileNumberJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobileNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumberJTextFieldActionPerformed(evt);
            }
        });

        pricePerDayJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pricePerDayJLabel.setText("Price Per Day");

        pricePerDayJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        numberOfDaysStayJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numberOfDaysStayJLabel.setText("Number of Days stay");

        numberOfDaysStayJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        totalPriceJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalPriceJLabel.setText("Total Price");

        totalPriceJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        emailJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailJLabel.setText("Email");

        emailJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        checkOutJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkOutJButton.setText("Check-Out");
        checkOutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutJButtonActionPerformed(evt);
            }
        });

        clearJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pricePerDayJLabel)
                                        .addGap(426, 426, 426)
                                        .addComponent(totalPriceJLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(checkOutJButton)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(closeButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(clearJButton)
                                                .addGap(0, 821, Short.MAX_VALUE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(75, 75, 75)
                                            .addComponent(roomNumberJLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(roomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(jButton2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(571, 571, 571)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(mobileNumberJLabel)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(mobileNumberJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                    .addComponent(emailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(emailJTextField)))))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(totalPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(customerNameJLabel)
                                                .addGap(164, 164, 164)
                                                .addComponent(checkInJLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(238, 238, 238)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(numberOfDaysStayJLabel)
                                                    .addComponent(checkInJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                    .addComponent(numberOfDaysStayJTextField))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(pricePerDayJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(238, 238, 238)))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkOutJLabel)
                                        .addComponent(checkOutJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(closeButton)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerNameJLabel)
                            .addComponent(checkInJLabel)
                            .addComponent(checkOutJLabel)
                            .addComponent(mobileNumberJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkInJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkOutJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mobileNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricePerDayJLabel)
                            .addComponent(numberOfDaysStayJLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalPriceJLabel)
                                .addComponent(emailJLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricePerDayJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfDaysStayJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomNumberJLabel)
                            .addComponent(roomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutJButton)
                    .addComponent(clearJButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        if (true) {
            dispose();
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void customerNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameJTextFieldActionPerformed

    private void mobileNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumberJTextFieldActionPerformed

    private void checkInJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInJTextFieldActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void checkOutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutJButtonActionPerformed
        // TODO add your handling code here:
        String Name = customerNameJTextField.getText();
        String mobileNumber = mobileNumberJTextField.getText();
        String email = emailJTextField.getText();

        String checkOut = checkOutJTextField.getText();
        String numberOfDaysStay = numberOfDaysStayJTextField.getText();
        String totalPrice = totalPriceJTextField.getText();
        String roomNumber = roomNumberJTextField.getText();
    }//GEN-LAST:event_checkOutJButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkInJLabel;
    private javax.swing.JTextField checkInJTextField;
    private javax.swing.JButton checkOutJButton;
    private javax.swing.JLabel checkOutJLabel;
    private javax.swing.JTextField checkOutJTextField;
    private javax.swing.JButton clearJButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTable customerInformationJTable;
    private javax.swing.JLabel customerNameJLabel;
    private javax.swing.JTextField customerNameJTextField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobileNumberJLabel;
    private javax.swing.JTextField mobileNumberJTextField;
    private javax.swing.JLabel numberOfDaysStayJLabel;
    private javax.swing.JTextField numberOfDaysStayJTextField;
    private javax.swing.JLabel pricePerDayJLabel;
    private javax.swing.JTextField pricePerDayJTextField;
    private javax.swing.JLabel roomNumberJLabel;
    private javax.swing.JTextField roomNumberJTextField;
    private javax.swing.JLabel totalPriceJLabel;
    private javax.swing.JTextField totalPriceJTextField;
    // End of variables declaration//GEN-END:variables
}
