/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import project.Data;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Asmz
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageRoomJButton = new javax.swing.JButton();
        customerCheckInJButton = new javax.swing.JButton();
        customerCheckOutJButton = new javax.swing.JButton();
        exitJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageRoomJButton.setBackground(new java.awt.Color(204, 204, 204));
        manageRoomJButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        manageRoomJButton.setForeground(new java.awt.Color(0, 102, 204));
        manageRoomJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage room.png"))); // NOI18N
        manageRoomJButton.setText("Manage  Room");
        manageRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRoomJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageRoomJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 211, 74));

        customerCheckInJButton.setBackground(new java.awt.Color(204, 204, 204));
        customerCheckInJButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        customerCheckInJButton.setForeground(new java.awt.Color(0, 102, 204));
        customerCheckInJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-in.png"))); // NOI18N
        customerCheckInJButton.setText("Customer Check-In");
        customerCheckInJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCheckInJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(customerCheckInJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        customerCheckOutJButton.setBackground(new java.awt.Color(204, 204, 204));
        customerCheckOutJButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        customerCheckOutJButton.setForeground(new java.awt.Color(0, 102, 204));
        customerCheckOutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-out.png"))); // NOI18N
        customerCheckOutJButton.setText("Customer Check-Out");
        customerCheckOutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCheckOutJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(customerCheckOutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        exitJButton.setBackground(new java.awt.Color(204, 204, 204));
        exitJButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        exitJButton.setForeground(new java.awt.Color(51, 153, 255));
        exitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background .jpg"))); // NOI18N
        jLabel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel2ComponentShown(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRoomJButtonActionPerformed
        // TODO add your handling code here:
        new ManageRoom().setVisible(true);
    }//GEN-LAST:event_manageRoomJButtonActionPerformed

    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Are You sure to Close the Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitJButtonActionPerformed

    private void jLabel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2ComponentShown

    private void customerCheckInJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCheckInJButtonActionPerformed
        // TODO add your handling code here:
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_customerCheckInJButtonActionPerformed

    private void customerCheckOutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCheckOutJButtonActionPerformed
        // TODO add your handling code here:
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_customerCheckOutJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Data.LoadTestDataRooms();
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerCheckInJButton;
    private javax.swing.JButton customerCheckOutJButton;
    private javax.swing.JButton exitJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageRoomJButton;
    // End of variables declaration//GEN-END:variables
}
