/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import project.Data;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.text.JTextComponent;
import javax.swing.table.DefaultTableModel;

import project.*;

/**
 *
 * @author Asmz
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form manageRoom
     */
    public ManageRoom() {
        initComponents();
        //  jTable1.r
        //jTable1.sete(false);
        ShowRooms();

    }

    private void ShowRooms() {
        DefaultTableModel model = (DefaultTableModel) manageRoomJTable.getModel();
        model.setRowCount(0);
        for (Room room : Data.rooms) {
            Object[] row = {room.getRoomNumber(), room.getRoomType(), room.getBed(), room.getPrice(), room.getAvailability(), room.getClean()};
            model.addRow(row);
        }
    }

    public ArrayList<Room> getRooms() {
        return Data.rooms;
    }

    public void addRoom(Room newRoom) {
        Data.rooms.add(newRoom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        manageRoomJLabel = new javax.swing.JLabel();
        colseJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageRoomJTable = new javax.swing.JTable();
        roomNumberJLabel = new javax.swing.JLabel();
        roomNumberJTextField = new javax.swing.JTextField();
        roomTypeJLabel = new javax.swing.JLabel();
        bedJLabel = new javax.swing.JLabel();
        bedJComboBox = new javax.swing.JComboBox<>();
        priceJLabel = new javax.swing.JLabel();
        priceJTextField = new javax.swing.JTextField();
        addRoomJButton = new javax.swing.JButton();
        ACJRadioButton = new javax.swing.JRadioButton();
        nonACJRadioButton = new javax.swing.JRadioButton();
        deleteRoomJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageRoomJLabel.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        manageRoomJLabel.setForeground(new java.awt.Color(51, 0, 0));
        manageRoomJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage room.png"))); // NOI18N
        manageRoomJLabel.setText("Manage Room");
        getContentPane().add(manageRoomJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 16, -1, -1));

        colseJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        colseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colseJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(colseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, -1));

        manageRoomJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price", "availabality", "clean"
            }
        ));
        jScrollPane1.setViewportView(manageRoomJTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 106, 575, -1));

        roomNumberJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomNumberJLabel.setText("Room Number");
        getContentPane().add(roomNumberJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 106, -1, -1));

        roomNumberJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 138, 465, -1));

        roomTypeJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomTypeJLabel.setText("Room Type");
        getContentPane().add(roomTypeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 182, -1, -1));

        bedJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bedJLabel.setText("Bed");
        getContentPane().add(bedJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 258, -1, -1));

        bedJComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bedJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        bedJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedJComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(bedJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 290, 465, -1));

        priceJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        priceJLabel.setText("Price (TL)");
        getContentPane().add(priceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 334, -1, -1));

        priceJTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(priceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 366, 465, -1));

        addRoomJButton.setBackground(new java.awt.Color(102, 0, 0));
        addRoomJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addRoomJButton.setForeground(new java.awt.Color(255, 255, 255));
        addRoomJButton.setText("Add Room");
        addRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addRoomJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 449, -1, -1));

        buttonGroup1.add(ACJRadioButton);
        ACJRadioButton.setText("AC");
        ACJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACJRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ACJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        buttonGroup1.add(nonACJRadioButton);
        nonACJRadioButton.setText("Non-AC");
        nonACJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonACJRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nonACJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, -1));

        deleteRoomJButton.setText("Delete Room");
        deleteRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteRoomJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bedJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bedJComboBoxActionPerformed

    private void roomNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberJTextFieldActionPerformed

    private void colseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colseJButtonActionPerformed
        // TODO add your handling code here:
        if (true) {
            dispose();
        }
    }//GEN-LAST:event_colseJButtonActionPerformed

    private void addRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomJButtonActionPerformed
        // TODO add your handling code here:
        // get data from the text fields and combo boxes
        String roomNumberString = roomNumberJTextField.getText();
        boolean ac = ACJRadioButton.isSelected();
        String roomType = ac ? "AC" : "Non-AC";
        String bed = (String) bedJComboBox.getSelectedItem();
        String priceString = priceJTextField.getText();
        String availability = "Available"; // set status to "Available" by default
        String clean = "Clean"; // set status to "Clean" by default

        // check if room number and price are not empty
        if (roomNumberString.isEmpty() || priceString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid room number and price.");
            return;
        }

        // attempt to parse the price as a double
        double priceDouble;
        try {
            priceDouble = Double.parseDouble(priceString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid price.");
            return;
        }

        // attempt to parse the room number as an integer
        int roomNumber;
        try {
            roomNumber = Integer.parseInt(roomNumberString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid room number.");
            return;
        }

        // check if the room number already exists
        for (Room room : Data.rooms) {
            if (room.getRoomNumber() == roomNumber) {
                JOptionPane.showMessageDialog(this, "Room number already exists.");
                return;
            }
        }

        // create a new Room object and add it to the Data.rooms ArrayList
        Room newRoom = new Room(roomNumber, ac, bed, priceDouble);
        Data.rooms.add(newRoom);

        // add a new row to the jTable1 table
        Object[] row = {roomNumber, roomType, bed, priceDouble, availability, clean};
        DefaultTableModel model = (DefaultTableModel) manageRoomJTable.getModel();
        model.addRow(row);
        JOptionPane.showMessageDialog(this, "Room added successfully!");

        // clear the text fields
        roomNumberJTextField.setText("");
        priceJTextField.setText("");

    }//GEN-LAST:event_addRoomJButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentShown

    private void ACJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACJRadioButtonActionPerformed

    private void nonACJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonACJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonACJRadioButtonActionPerformed

    private void deleteRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomJButtonActionPerformed
        // TODO add your handling code here:
        int row = manageRoomJTable.getSelectedRow();
        if (row >= 0) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this room?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) manageRoomJTable.getModel();
                model.removeRow(row);
                JOptionPane.showMessageDialog(this, "Room deleted successfully.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a room to delete.");
        }

        
    }//GEN-LAST:event_deleteRoomJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ACJRadioButton;
    private javax.swing.JButton addRoomJButton;
    private javax.swing.JComboBox<String> bedJComboBox;
    private javax.swing.JLabel bedJLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton colseJButton;
    private javax.swing.JButton deleteRoomJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageRoomJLabel;
    private javax.swing.JTable manageRoomJTable;
    private javax.swing.JRadioButton nonACJRadioButton;
    private javax.swing.JLabel priceJLabel;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JLabel roomNumberJLabel;
    private javax.swing.JTextField roomNumberJTextField;
    private javax.swing.JLabel roomTypeJLabel;
    // End of variables declaration//GEN-END:variables
}
